# Generated by Django 4.2.3 on 2023-07-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('bedrooms', models.CharField(max_length=25)),
                ('size', models.BigIntegerField()),
                ('bathrooms', models.CharField(max_length=25)),
                ('amenities', models.CharField(max_length=25)),
                ('price', models.TextField(max_length=25)),
                ('availability', models.TextField(max_length=25)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Houses',
        ),
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.properties'),
        ),
    ]
