# Generated by Django 4.2.3 on 2023-07-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_agent_properties_delete_houses_agent_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='owner',
            new_name='property',
        ),
        migrations.AddField(
            model_name='agent',
            name='fname',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='lname',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.FloatField(),
        ),
    ]
