# Generated by Django 4.2.3 on 2023-07-15 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0003_rename_owner_agent_property_agent_fname_agent_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='property',
        ),
        migrations.AlterField(
            model_name='properties',
            name='availability',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Booked'), (3, 'Taken')], default=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.agent'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.IntegerField(choices=[(1, 'Apartment'), (2, 'Hostel'), (3, 'Shared Apartment'), (5, 'Offices'), (6, 'Mixed Apartment with Offices')], default=6),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('phone', models.BigIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
